#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "photoview"
name = "Photoview"
description.en = "Simple and user-friendly photo gallery that's made for photographers "
description.fr = "Galerie photos simple et facile à utiliser, faite pour les photographes"

version = "2.4.0~ynh12"

maintainers = ["Jules Bertholet"]

[upstream]
license = "AGPL-3.0-only"
website = "https://photoview.github.io/"
demo = "https://photos.qpqp.dk/"
admindoc = "https://photoview.github.io/docs/"
code = "https://github.com/photoview/photoview"
fund = "https://github.com/sponsors/viktorstrate"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "1000M"
ram.build = "2000M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.mapbox_token]
    ask.en = "Mapbox API token"
    ask.fr = "Clé API Mapbox"
    help.en = "Required for mapping features. You can get one for free at https://www.mapbox.com/"
    help.fr = "Nécessaire pour les fonctionnalités cartographiques. Vous pouvez en obtenir une gratuitement à https://www.mapbox.com/"
    type = "string"
    default = ""
    optional = true

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://github.com/photoview/photoview/archive/517072890629c20ff9a0484703833799a70eed7a.tar.gz"
    sha256 = "cdd33d8aec4d953988bd3707ab69b8f48e5b013a299dacb82fa0d4d9a8919762"

    autoupdate.strategy = "latest_github_release"

    [resources.sources.vips_prebuilt_bookworm]
	url = "https://github.com/Thovi98/test/releases/download/vips-8.18.4-heif-1.23.1/vips-8.18.4-heif-1.23.1-bookworm.tar.gz"
	sha256 = "e958339824ed395cc4f7c4096fe570952c0fb32082391c2b96c23926373c8f3c"

    autoupdate.strategy = "latest_github_release"

	[resources.sources.vips_prebuilt_trixie]
	url = "https://github.com/Thovi98/test/releases/download/vips-8.18.4-heif-1.23.1/vips-8.18.4-heif-1.23.1-trixie.tar.gz"
	sha256 = "e4914a41a2b1b138565a334d6085179ceb47db1ff209b4cb284b50f0eea63307"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["media_cache"]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.protected = true

    share.url = "/share"
    share.allowed = "visitors"
    share.auth_header = false
    share.protected = true

    [resources.ports]
    main.default = 4001

    [resources.apt]
    packages = [
        "curl",
        "gpg",
        "ffmpeg",
        "ca-certificates",
        "libdlib-dev",
        "libblas-dev",
        "liblapack-dev",
        "libjpeg-dev",
        "build-essential",
        "pkg-config",
        "libx265-dev",
        "libde265-dev",
        "libaom-dev",
        # "darktable",
        "imagemagick",
        "libmagic-dev",
        "libmagickcore-dev",
        "libmagickwand-dev",
        "mariadb-server",
    ]

    packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bullseye" ]]; then
        echo "";
    elif [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "exiftool";
    elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
        echo "dpkg-dev libimage-exiftool-perl";
    fi
    """

    [resources.database]
    type = "mysql"

    [resources.nodejs]
    version = "18"

    [resources.go]
    version = "1.23"
